I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/level1.rpy", line 5, in script
    init -1 python:
  File "game/level1.rpy", line 5, in script
    init -1 python:
  File "game/level1.rpy", line 31, in <module>
    filel_d = DynamicDisplayable(get_file, fileContext)
NameError: name 'fileContext' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 515, in main
    renpy.game.context().run(node)
  File "game/level1.rpy", line 5, in script
    init -1 python:
  File "game/level1.rpy", line 5, in script
    init -1 python:
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/level1.rpy", line 31, in <module>
    filel_d = DynamicDisplayable(get_file, fileContext)
NameError: name 'fileContext' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.5.1648
powerplant 1.0
Sun May 30 12:00:25 2021
