I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 14, in script
    python:
  File "game/script.rpy", line 15, in <module>
    initGame()
  File "game/draggables.rpy", line 83, in initGame
    initLevels()
  File "game/draggables.rpy", line 90, in initLevels
    initLevel2()
  File "game/draggables.rpy", line 120, in initLevel2
    const_l2_folders.append( item_location(2, 51,413, Folder_BinM) )
NameError: global name 'Folder_BinM' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 14, in script
    python:
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 15, in <module>
    initGame()
  File "game/draggables.rpy", line 83, in initGame
    initLevels()
  File "game/draggables.rpy", line 90, in initLevels
    initLevel2()
  File "game/draggables.rpy", line 120, in initLevel2
    const_l2_folders.append( item_location(2, 51,413, Folder_BinM) )
NameError: global name 'Folder_BinM' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.5.1648
powerplant 1.0
Sun May 30 14:39:28 2021
