I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 30, in script
    e "Welcome to your first day at the power plant"
  File "game/script.rpy", line 30, in script
    e "Welcome to your first day at the power plant"
  File "game/draggables.rpy", line 110, in periodic_callback
    timer.Service()
  File "game/draggables.rpy", line 51, in Service
    self.callback(self.context)
  File "game/draggables.rpy", line 105, in PowerTimerCallback
    ui.interact()
Exception: Cannot start an interaction in the middle of an interaction, without creating a new context.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 617, in main
    run(restart)
  File "renpy/main.py", line 148, in run
    renpy.execution.run_context(True)
  File "renpy/execution.py", line 922, in run_context
    context.run()
  File "game/script.rpy", line 30, in script
    e "Welcome to your first day at the power plant"
  File "game/script.rpy", line 30, in script
    e "Welcome to your first day at the power plant"
  File "renpy/ast.py", line 715, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "renpy/exports.py", line 1417, in say
    who(what, *args, **kwargs)
  File "renpy/character.py", line 1219, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "renpy/character.py", line 871, in do_display
    **display_args)
  File "renpy/character.py", line 621, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "renpy/display/core.py", line 3213, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "renpy/display/core.py", line 3913, in interact_core
    i()
  File "game/draggables.rpy", line 110, in periodic_callback
    timer.Service()
  File "game/draggables.rpy", line 51, in Service
    self.callback(self.context)
  File "game/draggables.rpy", line 105, in PowerTimerCallback
    ui.interact()
  File "renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "renpy/display/core.py", line 3189, in interact
    raise Exception("Cannot start an interaction in the middle of an interaction, without creating a new context.")
Exception: Cannot start an interaction in the middle of an interaction, without creating a new context.

Windows-10-10.0.19041
Ren'Py 7.4.5.1648
powerplant 1.0
Sat May 29 23:45:02 2021
